site_name: AsterTrack Documentation
site_url: https://docs.astertrack.dev

repo_name: Doc Repo
repo_url: https://github.com/AsterTrack/AsterTrack_Documentation
edit_uri: edit/main/docs/
use_directory_urls: false

# Can't disable TOC globally, only per page
# toc.integrate + toc_depth 1 is the next best thing to get more horizontal space

theme:
  name: material
  logo: assets/astertrack_icon_white.svg
  favicon: assets/astertrack_favicon.png
  font: false
  features:
    - navigation.instant
    - navigation.expand
    - content.action.edit
    - content.action.view
    - toc.integrate
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: custom

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: custom
      accent: custom
extra_css: [
  extra.css
]
plugins:
  - privacy
  - search
  - social

markdown_extensions:
  - toc:
      toc_depth: "2"
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Overview: index.md
  - Building:
    - building/hardware.md
    - building/software.md
    - building/updating.md
  - Setup:
    - setup/camera_setup.md
    - setup/mounting_hardware.md
    - setup/wireless.md
    - setup/camera_calib.md
  - Operation:
    - operation/background.md
    - operation/recording.md
    - operation/issues.md
    - operation/safety.md
  - Tracking:
    - tracking/tracker_config.md
    - tracking/calib_target.md
    - tracking/calib_imu.md
    - tracking/integrations.md
  - Technical Details:
    - details/architecture.md
    - details/frame_timing.md
    - details/tracking_alg.md